import {
  Suraj,
  Kalyan,
  Aditya,
  Rajnish,
  Rudransh,
  Ravi,
  Shantanu,
  Prince,
  Ronak,
  Saumyajeet,
  Prriya,
  Sadhana,
  Adyasha,
  Nandan,
  Ayuska,
  Eklavya,
  Aurojyoti,
  Shwettam,
  Nishchal,
  Naina,
  Nilakshee,
  Amit,
  Arpit,
  Arunanshu,
  Soham,
  Priyanshu,
  Swayam,
  Mrutunjaya,
  Ankita,
  Reshma,
  Rohnit,
  Krishna,
  Biswajit,
} from "./index";

export const persons = [
    {
      id: "1",
      name: "Suraj Sharma",
      department: "Former Cloud Computing Lead, IIIT-Bh",
      role: "Founder",
      image: Suraj,
      links: {
        instagram: "",
        linkedin: "https://www.linkedin.com/in/drsurajsharma/",
        github: "https://github.com/kalyansrinivas001",
        email: "suraj.cse@ggu.ac.in",
      },
    },
    {
      id: "2",
      name: "Kalyan Srinivas",
      department: "M.Tech, CSE (2020-2022)",
      role: "Co-Founder",
      image: Kalyan,
      links: {
        instagram: "https://www.instagram.com/kalyan.klikbox/",
        linkedin: "https://www.linkedin.com/in/kalyan-srinivas-6b0796111/",
        github: "https://github.com/kalyansrinivas001",
        email: "a120001@iiit-bh.ac.in",
      },
    },
    {
      id: "3",
      name: "Aditya Raj",
      department: "CSE",
      role: "Advisor",
      image: Aditya,
      links: {
        instagram: "https://www.instagram.com/adityarajkishan/",
        linkedin: "https://www.linkedin.com/in/aditya-raj-kishan",
        github: "https://github.com/Adityarajkishan",
        email: "https://github.com/Adityarajkishan",
      },
    },
    {
      id: "4",
      name: "Rajnish Kumar Singh",
      department: "CSE",
      role: "Secretary (2023-24)",
      image: Rajnish,
      links: {
        instagram: "https://www.instagram.com/rks_031",
        linkedin: "https://www.linkedin.com/in/rajnish-kumar-singh-2241b321b/",
        github: "https://github.com/rks-031",
        email: "rajnish31july@gmail.com",
      },
    },
    {
      id: "5",
      name: "Rudransh Agrawal",
      department: "CSE",
      role: "Joint-Secretary (2023-24)",
      image: Rudransh,
      links: {
        instagram: "https://www.instagram.com/tech__freak?igsh=ZmFuOXRzajRnMm5j",
        linkedin: "https://www.linkedin.com/in/rudransh-agrawal-6a6645172",
        email: "rudransh.agrawal980@gmail.com",
      },
    },
    {
      id: "6",
      name: "Ravi Sovesh",
      department: "CSE",
      role: "Joint Secretary (2023-24)",
      image: Ravi,
      links: {
        instagram: "https://www.instagram.com/v.ilen?igsh=MXh0ZGxpMDh5Y290cw%3D%3D&utm_source=qr",
        email: "soveshhere@gmail.com",
      },
    },
    {
      id: "7",
      name: "A Shantanu",
      department: "Customer Service",
      role: "Customer Service Representative",
      image: Shantanu,
      links: {
        instagram: "https://www.instagram.com/shaan_4712/",
        linkedin: "https://www.linkedin.com/in/shantanu4712/",
        github: "https://github.com/shaan4712",
        email: "shaan2k3@gmail.com",
      },
    },
    {
      id: "8",
      name: "Prince Kumar Singh",
      department: "Operations",
      role: "Operations Manager",
      image: Prince,
      links: {
        instagram: "https://www.instagram.com/michaelwilson/",
        linkedin: "https://www.linkedin.com/in/michaelwilson/",
        github: "https://github.com/michaelwilson",
        email: "michaelwilson@example.com",
        twitter: "https://twitter.com/michaelwilson/",
      },
    },
    {
      id: "9",
      name: "Biswajit Bhoi",
      department: "Research and Development",
      role: "Research Scientist",
      image: Biswajit,
      links: {
        instagram: "https://www.instagram.com/oliviaanderson/",
        linkedin: "https://www.linkedin.com/in/oliviaanderson/",
        github: "https://github.com/oliviaanderson",
        email: "oliviaanderson@example.com",
        twitter: "https://twitter.com/oliviaanderson/",
      },
    },
    {
      id: "10",
      name: "Ronak Agrawal",
      department: "Product Management",
      role: "Product Manager",
      image: Ronak,
      links: {
        instagram: "https://www.instagram.com/williamthompson/",
        linkedin: "https://www.linkedin.com/in/williamthompson/",
        github: "https://github.com/williamthompson",
        email: "williamthompson@example.com",
        twitter: "https://twitter.com/williamthompson/",
      },
    },
    {
      id: "11",
      name: "Sadhana Panigraphy",
      department: "Quality Assurance",
      role: "QA Engineer",
      image: "/path/to/image11.jpg",
      links: {
        instagram: "https://www.instagram.com/emilygarcia/",
        linkedin: "https://www.linkedin.com/in/emilygarcia/",
        github: "https://github.com/emilygarcia",
        email: "emilygarcia@example.com",
        twitter: "https://twitter.com/emilygarcia/",
      },
    },
    {
      id: "12",
      name: "Adyasha Mohanty",
      department: "Legal",
      role: "Legal Counsel",
      image: "/path/to/image12.jpg",
      links: {
        instagram: "https://www.instagram.com/danielmartinez/",
        linkedin: "https://www.linkedin.com/in/danielmartinez/",
        github: "https://github.com/danielmartinez",
        email: "danielmartinez@example.com",
        twitter: "https://twitter.com/danielmartinez/",
      },
    },
    {
      id: "13",
      name: "Saumyajeet Verma",
      department: "Public Relations",
      role: "PR Manager",
      image: "/path/to/image13.jpg",
      links: {
        instagram: "https://www.instagram.com/avarodriguez/",
        linkedin: "https://www.linkedin.com/in/avarodriguez/",
        github: "https://github.com/avarodriguez",
        email: "avarodriguez@example.com",
        twitter: "https://twitter.com/avarodriguez/",
      },
    },
    {
      id: "14",
      name: "Nandan Roy",
      department: "Business Development",
      role: "Business Development Manager",
      image: "/path/to/image14.jpg",
      links: {
        instagram: "https://www.instagram.com/jameslee/",
        linkedin: "https://www.linkedin.com/in/jameslee/",
        github: "https://github.com/jameslee",
        email: "jameslee@example.com",
        twitter: "https://twitter.com/jameslee/",
      },
    },
    {
      id: "15",
      name: "Eklavya Kumar",
      department: "Design",
      role: "Graphic Designer",
      image: "/path/to/image15.jpg",
      links: {
        instagram: "https://www.instagram.com/sofiahernandez/",
        linkedin: "https://www.linkedin.com/in/sofiahernandez/",
        github: "https://github.com/sofiahernandez",
        email: "sofiahernandez@example.com",
        twitter: "https://twitter.com/sofiahernandez/",
      },
    },
    {
      id: "16",
      name: "Aurojyoti Das",
      department: "Customer Success",
      role: "Customer Success Manager",
      image: "/path/to/image16.jpg",
      links: {
        instagram: "https://www.instagram.com/benjaminperez/",
        linkedin: "https://www.linkedin.com/in/benjaminperez/",
        github: "https://github.com/benjaminperez",
        email: "benjaminperez@example.com",
        twitter: "https://twitter.com/benjaminperez/",
      },
    },
    {
      id: "17",
      name: "Ayuska Choudhary",
      department: "Training and Development",
      role: "Training Manager",
      image: "/path/to/image17.jpg",
      links: {
        instagram: "https://www.instagram.com/miamoore/",
        linkedin: "https://www.linkedin.com/in/miamoore/",
        github: "https://github.com/miamoore",
        email: "miamoore@example.com",
        twitter: "https://twitter.com/miamoore/",
      },
    },
    {
      id: "18",
      name: "Shwettam Sahu",
      department: "Education",
      role: "Education Coordinator",
      image: "/path/to/image18.jpg",
      links: {
        instagram: "https://www.instagram.com/henrymartin/",
        linkedin: "https://www.linkedin.com/in/henrymartin/",
        github: "https://github.com/henrymartin",
        email: "henrymartin@example.com",
        twitter: "https://twitter.com/henrymartin/",
      },
    },
    {
      id: "19",
      name: "Nishchal Verma",
      department: "Healthcare",
      role: "Medical Director",
      image: "/path/to/image19.jpg",
      links: {
        instagram: "https://www.instagram.com/chloejackson/",
        linkedin: "https://www.linkedin.com/in/chloejackson/",
        github: "https://github.com/chloejackson",
        email: "chloejackson@example.com",
        twitter: "https://twitter.com/chloejackson/",
      },
    },
    {
      id: "20",
      name: "Naina Purohit",
      department: "Logistics",
      role: "Logistics Manager",
      image: "/path/to/image20.jpg",
      links: {
        instagram: "https://www.instagram.com/liamwhite/",
        linkedin: "https://www.linkedin.com/in/liamwhite/",
        github: "https://github.com/liamwhite",
        email: "liamwhite@example.com",
        twitter: "https://twitter.com/liamwhite/",
      },
    },
    {
      id: "21",
      name: "Nilakshee Sahu",
      department: "Facilities",
      role: "Facilities Manager",
      image: "/path/to/image21.jpg",
      links: {
        instagram: "https://www.instagram.com/charlotteharris/",
        linkedin: "https://www.linkedin.com/in/charlotteharris/",
        github: "https://github.com/charlotteharris",
        email: "charlotteharris@example.com",
        twitter: "https://twitter.com/charlotteharris/",
      },
    },
    {
      id: "22",
      name: "Priyanshu Shekhar",
      department: "Information Technology",
      role: "IT Manager",
      image: "/path/to/image22.jpg",
      links: {
        instagram: "https://www.instagram.com/noahnelson/",
        linkedin: "https://www.linkedin.com/in/noahnelson/",
        github: "https://github.com/noahnelson",
        email: "noahnelson@example.com",
        twitter: "https://twitter.com/noahnelson/",
      },
    },
    {
      id: "23",
      name: "Chandrika",
      department: "Administration",
      role: "Administrative Assistant",
      image: "/path/to/image23.jpg",
      links: {
        instagram: "https://www.instagram.com/graceperez/",
        linkedin: "https://www.linkedin.com/in/graceperez/",
        github: "https://github.com/graceperez",
        email: "graceperez@example.com",
        twitter: "https://twitter.com/graceperez/",
      },
    },
    {
      id: "24",
      name: "Reshma Talari",
      department: "Security",
      role: "Security Officer",
      image: "/path/to/image24.jpg",
      links: {
        instagram: "https://www.instagram.com/jacktaylor/",
        linkedin: "https://www.linkedin.com/in/jacktaylor/",
        github: "https://github.com/jacktaylor",
        email: "jacktaylor@example.com",
        twitter: "https://twitter.com/jacktaylor/",
      },
    },
    {
      id: "25",
      name: "Ankita Priyadarshini",
      department: "Legal",
      role: "Paralegal",
      image: "/path/to/image25.jpg",
      links: {
        instagram: "https://www.instagram.com/ariathomas/",
        linkedin: "https://www.linkedin.com/in/ariathomas/",
        github: "https://github.com/ariathomas",
        email: "ariathomas@example.com",
        twitter: "https://twitter.com/ariathomas/",
      },
    },
    {
      id: "26",
      name: "Anwesha Priyadarshini",
      department: "Engineering",
      role: "Engineering Manager",
      image: "/path/to/image26.jpg",
      links: {
        instagram: "https://www.instagram.com/ethanwalker/",
        linkedin: "https://www.linkedin.com/in/ethanwalker/",
        github: "https://github.com/ethanwalker",
        email: "ethanwalker@example.com",
        twitter: "https://twitter.com/ethanwalker/",
      },
    },
    {
      id: "27",
      name: "Amit Kumar Hota",
      department: "Operations",
      role: "Operations Coordinator",
      image: "/path/to/image27.jpg",
      links: {
        instagram: "https://www.instagram.com/addisonlewis/",
        linkedin: "https://www.linkedin.com/in/addisonlewis/",
        github: "https://github.com/addisonlewis",
        email: "addisonlewis@example.com",
        twitter: "https://twitter.com/addisonlewis/",
      },
    },
    {
      id: "28",
      name: "Arpit Raj",
      department: "Finance",
      role: "Finance Manager",
      image: "/path/to/image28.jpg",
      links: {
        instagram: "https://www.instagram.com/madisonhall/",
        linkedin: "https://www.linkedin.com/in/madisonhall/",
        github: "https://github.com/madisonhall",
        email: "madisonhall@example.com",
        twitter: "https://twitter.com/madisonhall/",
      },
    },
    {
      id: "29",
      name: "Arunanshu Arya",
      department: "Customer Support",
      role: "Customer Support Specialist",
      image: "/path/to/image29.jpg",
      links: {
        instagram: "https://www.instagram.com/lunayoung/",
        linkedin: "https://www.linkedin.com/in/lunayoung/",
        github: "https://github.com/lunayoung",
        email: "lunayoung@example.com",
        twitter: "https://twitter.com/lunayoung/",
      },
    },
    {
      id: "30",
      name: "Soham Mishra",
      department: "Marketing",
      role: "Marketing Coordinator",
      image: "/path/to/image30.jpg",
      links: {
        instagram: "https://www.instagram.com/lucasking/",
        linkedin: "https://www.linkedin.com/in/lucasking/",
        github: "https://github.com/lucasking",
        email: "lucasking@example.com",
        twitter: "https://twitter.com/lucasking/",
      },
    },
    {
      id: "31",
      name: "Swayam Aryaaman",
      department: "Human Resources",
      role: "HR Coordinator",
      image: "/path/to/image31.jpg",
      links: {
        instagram: "https://www.instagram.com/scarlettwright/",
        linkedin: "https://www.linkedin.com/in/scarlettwright/",
        github: "https://github.com/scarlettwright",
        email: "scarlettwright@example.com",
        twitter: "https://twitter.com/scarlettwright/",
      },
    },
    {
      id: "32",
      name: "Mrutunjaya Panda",
      department: "Sales",
      role: "Sales Manager",
      image: "/path/to/image32.jpg",
      links: {
        instagram: "https://www.instagram.com/hunterlopez/",
        linkedin: "https://www.linkedin.com/in/hunterlopez/",
        github: "https://github.com/hunterlopez",
        email: "hunterlopez@example.com",
        twitter: "https://twitter.com/hunterlopez/",
      },
    },
    {
      id: "33",
      name: "Krishna",
      department: "Business Development",
      role: "Business Development Specialist",
      image: "/path/to/image33.jpg",
      links: {
        instagram: "https://www.instagram.com/victoriahill/",
        linkedin: "https://www.linkedin.com/in/victoriahill/",
        github: "https://github.com/victoriahill",
        email: "victoriahill@example.com",
        twitter: "https://twitter.com/victoriahill/",
      },
    },
    {
      id: "34",
      name: "Rohnit Guru",
      department: "Quality Assurance",
      role: "QA Analyst",
      image: "/path/to/image34.jpg",
      links: {
        instagram: "https://www.instagram.com/gabrielbaker/",
        linkedin: "https://www.linkedin.com/in/gabrielbaker/",
        github: "https://github.com/gabrielbaker",
        email: "gabrielbaker@example.com",
        twitter: "https://twitter.com/gabrielbaker/",
      },
    },
    {
      id: "35",
      name: "Akshita",
      department: "Public Relations",
      role: "PR Specialist",
      image: "/path/to/image35.jpg",
      links: {
        instagram: "https://www.instagram.com/natalieallen/",
        linkedin: "https://www.linkedin.com/in/natalieallen/",
        github: "https://github.com/natalieallen",
        email: "natalieallen@example.com",
        twitter: "https://twitter.com/natalieallen/",
      },
    },
    {
      id: "36",
      name: "Akshita",
      department: "Engineering",
      role: "Software Engineer",
      image: "/path/to/image36.jpg",
      links: {
        instagram: "https://www.instagram.com/christopherscott/",
        linkedin: "https://www.linkedin.com/in/christopherscott/",
        github: "https://github.com/christopherscott",
        email: "christopherscott@example.com",
        twitter: "https://twitter.com/christopherscott/",
      },
    },
  ];
  