import {
  Suraj,
  Kalyan,
  Aditya,
  Saswati,
  Rajnish,
  Rudransh,
  Ravi,
  Shantanu,
  Prince,
  Ronak,
  Saumyajeet,
  Prriya,
  Sadhana,
  Adyasha,
  Nandan,
  Ayuska,
  Eklavya,
  Aurojyoti,
  Shwettam,
  Nishchal,
  Naina,
  Nilakshee,
  Amit,
  Arpit,
  Arunanshu,
  Soham,
  Akshita,
  Priyanshu,
  Swayam,
  Mrutunjaya,
  Ankita,
  Reshma,
  Rohnit,
  Krishna,
  Biswajit,
  Anwesha,
  chandrika
} from "./index";

export const persons = [
    {
      id: "1",
      name: "Suraj Sharma",
      department: "Former Cloud Computing Lead, IIIT-Bh",
      role: "Founder",
      image:Suraj ,
      links: {
        instagram: "",
        linkedin: "https://www.linkedin.com/in/drsurajsharma/",
        github: "https://github.com/kalyansrinivas001",
        email: "suraj.cse@ggu.ac.in",
      },
    },
    {
      id: "2",
      name: "Kalyan Srinivas",
      department: "M.Tech, CSE (2020-2022)",
      role: "Co-Founder",
      image: Kalyan,
      links: {
        instagram: "https://www.instagram.com/kalyan.klikbox/",
        linkedin: "https://www.linkedin.com/in/kalyan-srinivas-6b0796111/",
        github: "https://github.com/kalyansrinivas001",
        email: "a120001@iiit-bh.ac.in",
      },
    },
    {
      id: "3",
      name: "Aditya Raj",
      department: "CSE",
      role: "Establishing Founder & Advisor",
      image: Aditya,
      links: {
        instagram: "https://www.instagram.com/adityarajkishan/",
        linkedin: "https://www.linkedin.com/in/aditya-raj-kishan",
        github: "https://github.com/Adityarajkishan",
        email: "https://github.com/Adityarajkishan",
      },
    },
    {
      id: "4",
      name: "Saswati Parida",
      department: "EEE",
      role: "Mentor",
      image: Saswati,
      links: {
        instagram: "https://www.instagram.com/sashwatii_?igsh=MWp2bTM3bDQ4dnI0bg== ",
        linkedin: "https://www.linkedin.com/in/saswati-parida-980910213?originalSubdomain=in",
        github: "https://github.com/sashwati2309",
        email: "saswatiparidarisha@gmail.com",
      },
    },
    {
      id: "4",
      name: "Rajnish Kumar Singh",
      department: "CSE",
      role: "Secretary (2023-24)",
      image: Rajnish,
      links: {
        instagram: "https://www.instagram.com/rks_031",
        linkedin: "https://www.linkedin.com/in/rajnish-kumar-singh-2241b321b/",
        github: "https://github.com/rks-031",
        email: "rajnish31july@gmail.com",
      },
    },
    {
      id: "5",
      name: "Rudransh Agrawal",
      department: "CSE",
      role: "Joint-Secretary (2023-24)",
      image: Rudransh,
      links: {
        instagram: "https://www.instagram.com/tech__freak?igsh=ZmFuOXRzajRnMm5j",
        linkedin: "https://www.linkedin.com/in/rudransh-agrawal-6a6645172",
        email: "rudransh.agrawal980@gmail.com",
      },
    },
    {
      id: "6",
      name: "Ravi Sovesh",
      department: "CSE",
      role: "Joint Secretary (2023-24)",
      image: Ravi,
      links: {
        instagram: "https://www.instagram.com/v.ilen?igsh=MXh0ZGxpMDh5Y290cw%3D%3D&utm_source=qr",
        email: "soveshhere@gmail.com",
      },
    },
    {
      id: "7",
      name: "A Shantanu",
      department: "IT",
      role: "Editing Lead (2023-24)",
      image: Shantanu,
      links: {
        instagram: "https://www.instagram.com/shaan_4712/",
        linkedin: "https://www.linkedin.com/in/shantanu4712/",
        github: "https://github.com/shaan4712",
        email: "shaan2k3@gmail.com",
      },
    },
    {
      id: "8",
      name: "Prince Kumar Singh",
      department: "CE",
      role: "Secretary (2024-25)",
      image: Prince,
      links: {
        instagram: "https://www.instagram.com/prince_k2608?igsh=MTAzM3dpaHlpemdqZw==",
        linkedin: "http://www.linkedin.com/in/prince-kumar-singh-00804025b",
        github: "https://github.com/Prince-Ku-S",
        email: "princesinghv35@gmail.com",
      },
    },
    {
      id: "9",
      name: "Biswajit Bhoi",
      department: "CE",
      role: "Joint Secretary (2024-25)",
      image: Biswajit,
      links: {
        instagram: "https://www.instagram.com/biswajit.bhoi.125/",
        linkedin: "https://www.linkedin.com/in/biswajit-bhoi-2537b5257/",
        github: "https://github.com/biswajit522016",
        email: "b522016@iiit-bh.ac.in",
      },
    },
    {
      id: "10",
      name: "Ronak Agrawal",
      department: "CE",
      role: "Joint Secretary (2024-25)",
      image: Ronak,
      links: {
        instagram: "https://www.instagram.com/ronakagrawal39?igsh=NHI1eTF3azljcnV1",
        linkedin: "https://www.linkedin.com/in/ronak-agrawal-95994812b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        Portfolio_Acc: "https://www.instagram.com/ronakag_portfolio?igsh=MTJ0a3l0cjR0OW9xaA==",
        email: "ronakagrawal39@gmail.com",
      },
    },
    {
      id: "11",
      name: "Sadhana Panigraphy",
      department: "ETC",
      role: "Event Management Lead (2024-25)",
      image: Sadhana,
      links: {
        instagram: "https://www.instagram.com/_sadhanaa_a?igsh=MTJ0YzFoa2ljdWwzMA==",
        linkedin: "https://www.linkedin.com/in/sadhana-panigrahi-420b09260?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        email: "b222042@iiit-bh.ac.in",
      },
    },
    {
      id: "12",
      name: "Prriya Bandita Dash",
      department: "ETC",
      role: "Content Lead (2024-25)",
      image: Prriya,
      links: {
        instagram: "https://instagram.com/_blue.shades?igshid=ZDdkNTZiNTM=",
        linkedin: "https://www.linkedin.com/in/prriya-dash-33234a263",
        github:"https://github.com/PrriyaBandita-2002",
        email: "b222039@iiit-bh.ac.in",
      },
    },
    {
      id: "13",
      name: "Adyasha Mohanty",
      department: "CSE",
      role: "Podcast Lead (2024-25)",
      image: Adyasha,
      links: {
        instagram: "https://www.instagram.com/addyctive.16?igsh=OGQ5ZDc2ODk2ZA==",
        email: "b122009@iiit-bh.ac.in",
      },
    },
    {
      id: "14",
      name: "Saumyajeet Verma",
      department: "CE",
      role: "Graphics Lead (2024-25)",
      image: Saumyajeet,
      links: {
        instagram: "https://www.instagram.com/_saumyajeet_/",
        linkedin: "https://www.linkedin.com/in/saumyajeet-varma-91bb4025a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/Saumyajeet-Varma",
        email: "b522053@iiit-bh.ac.in",
      },
    },
    {
      id: "15",
      name: "Nandan Roy",
      department: "CE",
      role: "Editing Lead (2024-25)",
      image: Nandan,
      links: {
        instagram: "https://www.instagram.com/roy._68?igsh=ZWVldXQ0NXFocHFl",
        linkedin: "https://www.linkedin.com/in/nandan-roy-771b4225a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        email: "b522038@iiit-bh.ac.in",
        YouTube:"https://youtube.com/@naroy2901?si=cjlQi6nlTkfzK6qY",
      },
    },
    {
      id: "16",
      name: "Eklavya Kumar",
      department: "CE",
      role: "Core",
      image: Eklavya,
      links: {
        instagram: "https://www.instagram.com/eklavy_a0/",
        linkedin: "https://www.linkedin.com/in/eklavya-kumar-5a1435255/",
        github: "https://github.com/Eklavya-Kumar",
        email: "eklavya6200@gmail.com",
      },
    },
    {
      id: "17",
      name: "Aurojyoti Das",
      department: "IT",
      role: "Core",
      image: Aurojyoti,
      links: {
        instagram: "https://www.instagram.com/aurojr__18?igsh=dzB1eHZtZ3g1MTM4",
        linkedin: "https://www.linkedin.com/in/aurojyoti-das-0454a7216?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/auro19d",
        email: "b422017@iiit-bh.ac.in",
      },
    },
    {
      id: "18",
      name: "Ayuska Choudhary",
      department: "ETC",
      role: "Core",
      image: Ayuska,
      links: {
        instagram: "https://www.instagram.com/ayuska_.13_",
        linkedin: "https://www.linkedin.com/in/ayuska-choudhary-0141b4255",
        github: "https://github.com/ayuskac13",
        email: "ayuskac13@gmail.com",
      },
    },
    {
      id: "19",
      name: "Shwettam Sahu",
      department: "IT",
      role: "Squad",
      image: Shwettam,
      links: {
        instagram: "https://www.instagram.com/s_sahu20?igsh=eWFrZ2RucWpyMXlv",
        linkedin: "https://www.linkedin.com/in/shwettam-sahu-959a13214?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/Shwettam",
        email: "shwettamsahu8076@gmail.com",
      },
    },
    {
      id: "20",
      name: "Nishchal Verma",
      department: "IT",
      role: "Squad",
      image: Nishchal,
      links: {
        instagram: "https://www.instagram.com/.nixchal.?igsh=MWM4Z3ZwemNqOG9oOA==",
        linkedin: "https://www.linkedin.com/in/nishchal-verma-497129245?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/Nixchal2004",
        email: "b423042@iiitbh.ac.in",
        Behance:"https://www.behance.net/gfxnishchalverma",
      },
    },
    {
      id: "21",
      name: "Naina Purohit",
      department: "IT",
      role: "Squad",
      image: Naina,
      links: {
        instagram: "https://www.instagram.com/nainapurohit12?igsh=MTV2dmNlZnRqbzV3aA==",
        linkedin: "https://www.linkedin.com/in/naina-purohit-64bb38283?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/nainapurohit",
        email: "b423039@iiit-bh.ac.in",
      },
    },
    {
      id: "22",
      name: "Nilakshee Sahu",
      department: "CSE",
      role: "Squad",
      image: Nilakshee,
      links: {
        instagram: "https://www.instagram.com/nilakshee_sahu?igsh=MWtqeHphYXI0dXNmYQ==",
        github: "https://github.com/nilakshee-sahu",
        email: "b123078@iiit-bh.ac.in",
      },
    },
    {
      id: "23",
      name: "Priyanshu Shekhar",
      department: "EEE",
      role: "Squad",
      image: Priyanshu,
      links: {
        email: "b323027@iiit-bh.ac.in",
      },  
    },
    {
      id: "24",
      name: "Patnana Chandrika",
      department: "CSE",
      role: "Squad",
      image: chandrika,
      links: {
        instagram: "https://www.instagram.com/patnana__chandrika?igsh=amU3OTU1bWJuaXBv",
        email: "b123087@iiit-bh.ac.in",
      },
    },
    {
      id: "25",
      name: "Reshma Talari",
      department: "CE",
      role: "Squad",
      image: Reshma,
      links: {
        instagram: "https://www.instagram.com/reshmatalari?igsh=MWxjZGN4azkzZ2l3cA==",
        email: "b523071@iiit-bh.ac.in",
      },
    },
    {
      id: "26",
      name: "Ankita Priyadarshini",
      department: "CE",
      role: "Squad",
      image: Ankita,
      links: {
        instagram: "https://www.instagram.com/ankita.mp4?igsh=MWhoajgyMnZocWNscQ==",
        email: "b523006@iiit-bh.ac.in",
      },
    },
    {
      id: "27",
      name: "Anwesha Priyadarshini",
      department: "CE",
      role: "Squad",
      image: Anwesha,
      links: {
        instagram: "https://www.instagram.com/_anwesha2k17_?igsh=MWlucGN5NnAwNWxnNg==",
        email: "b523009@iiit-bh.ac.in",
      },
    },
    {
      id: "28",
      name: "Amit Kumar Hota",
      department: "CSE",
      role: "Squad",
      image: Amit,
      links: {
        instagram: "https://www.instagram.com/ameexx._?igsh=cW1qN2xxNnJqbGxv",
        linkedin: "https://www.linkedin.com/in/amit-kumar-hota-68070a2b3?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        email: "amit.kumarhota123987@gmail.com",
      },
    },
    {
      id: "29",
      name: "Arpit Raj",
      department: "CSE",
      role: "Squad",
      image: Arpit,
      links: {
        instagram: "https://www.instagram.com/arpitrajj_",
        github: "https://github.com/arpit-rajj",
        email: "b123024@iiit-bh.ac.in",
      },
    },
    {
      id: "30",
      name: "Arunanshu Arya",
      department: "CE",
      role: "Squad",
      image: Arunanshu,
      links: {
        instagram: "https://www.instagram.com/arunanshuarya?igsh=dDd3YXVuZW1zN2J5",
        linkedin: "https://www.linkedin.com/in/arunanshu-arya-347911298",
        github: "https://github.com/Arunanshu-Arya",
        email: "b523013@iiit-bh.ac.in",
        twitter: "https://x.com/arunanshu_arya?t=GIRCyoD5qwZ30ANnhMGKhQ&s=09",
      },
    },
    {
      id: "31",
      name: "Soham Mishra",
      department: "IT",
      role: "Squad",
      image: Soham,
      links: {
        instagram: "https://www.instagram.com/soham_mishra2004",
        linkedin: "http://www.linkedin.com/in/soham-mishra-ind/",
        github: "https://github.com/Soham-India",
        email: "b323027@iiit-bh.ac.in",
      },
    },
    {
      id: "32",
      name: "Swayam Aryaaman",
      department: "IT",
      role: "Squad",
      image: Swayam,
      links: {
        instagram: "https://www.instagram.com/aryamanswayam?igsh=MTY5bWdqajRiZTM3Zw==",
        email: "b423069@iiit-bh.ac.in",
      },
    },
    {
      id: "33",
      name: "Mrutunjaya Panda",
      department: "CSE",
      role: "Squad",
      image: Mrutunjaya,
      links: {
        instagram: "https://www.instagram.com/kingstar_28?igsh=MXM1a3MweDRkZnp0eA==",
        linkedin: "https://www.linkedin.com/in/mrutunjaya-panda?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/Mrutunjaya-Panda",
        email: "mrutunjayapanda28@gmail.com",
      },
    },
    {
      id: "34",
      name: "Krishna Kaushik Barik",
      department: "CSE",
      role: "Squad",
      image: Krishna,
      links: {
        instagram: "https://www.instagram.com/krishnakausikbarik/",
        linkedin: "https://www.linkedin.com/in/krishna-kausik-barik-33306b293/",
        email: "krishnakaushik642@gmail.com",
        YouTube:"https://www.youtube.com/@krishnakausikbarik",
        Facebook:"https://www.facebook.com/krishnakausikbarik",
      },
    },
    {
      id: "35",
      name: "Rohnit Guru",
      department: "EEE",
      role: "Squad",
      image: Rohnit,
      links: {
        instagram: "https://www.instagram.com/rohnit_guru_2003?igsh=cDh4dWNpZWJqbXlj",
        linkedin: "https://www.linkedin.com/in/rohnit-guru-1aa64329b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        email: "b323031@iiit-bh.ac.in",
      },
    },
    {
      id: "36",
      name: "Akshita Nayak",
      department: "IT",
      role: "Squad", 
      image: Akshita,
      links: {
        instagram: "https://www.instagram.com/akxshitaaa.?igsh=MWMxaWQ4MmxjcHkxZg==",
        email: "b423006@iiit-bh.ac.in",
      },
    },
  ];
  